### ISSUE TITLE
Optionally tag the git commit with the balena release version

### ISSUE THREAD

**Issue by klutchell** [balena-io/balena-ci#17]
Close the loop by getting the balena release raw version from the API and attempting to tag the git commit.

Allow this step to fail occasionally as sometimes the balena release raw version will already match the last versionbot tag.

Here's how to accomplish this manually today, but it would be nice to have it as a boolean feature of the action.

```yml
    steps:
      - uses: actions/checkout@v2

      - id: balena_ci
        uses: balena-io/balena-ci@klutchell/pin-versions
        with:
          balena_token: ${{ secrets.BALENA_API_KEY }}
          fleet: ${{ secrets.BALENA_FLEET_SLUG }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          versionbot: true
          environment: balena-cloud.com

      - id: balena_api
        shell: bash
        run: |
          raw_version="$(curl -fsSL -X GET \
            "https://api.balena-cloud.com/v6/release(${{ steps.balena_ci.outputs.release_id }})?\$select=version" \
            -H "Content-Type: application/json" -H "Authorization: Bearer ${{ secrets.BALENA_API_KEY }}" | jq -r '.d[].version.raw')"
          echo "::set-output name=raw_version::$raw_version"

      - id: tagger
        uses: tvdias/github-tagger@v0.0.2
        continue-on-error: true
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "v${{ steps.balena_api.outputs.raw_version }}"
```
